config/routes.rb
Rails.application.routes.draw do
  root 'cards#index'
  resources :cards
end

app/models/card.rb
class Card < ActiveRecord::Base

  before_save :set_review_date
  validates :original_text, :translated_text, :review_date, presence: true
  validate  :translated_not_original

  def translated_not_original
  	if translated_text.downcase == original_text.downcase
  	  errors.add(:original_text, "Error")
    end
  end
  
  def set_review_date
    self.review_date == 3.days.from_now
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :find_card, only: [:show, :edit, :update, :destroy]

  def index
  	@cards = Card.all
  end

  def new
    @card = Card.new
  end

  def create
    @card = Card.new(card_params)
    if @card.save
      redirect_to @card
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
  	if @card.update(card_params)
  	  redirect_to @card
  	else
      render 'edit'
  	end
  end

  def destroy
    @card.destroy
    redirect_to cards_path
  end

  private

  def find_card
  	@card = Card.find(params[:id])
  end

  def card_params
  	params.require(:card).permit(:original_text, :translated_text)
  end

end

app/controllers/cards_controller_controller.rb
class CardsControllerController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_controller_helper.rb
module CardsControllerHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/edit.html.erb
<%= simple_form_for @card do |f| %>
  <%= f.input :original_text %>
  <%= f.input :translated_text %>
  <%= f.button :submit %>
<% end %>

app/views/cards/index.html.erb
<h1>All Cards</h1>

<table class="table">
 <tr>
   <th>Original Text</th>
   <th>Translated Text</th>
   <th>Date</th>
   <th colspan="2"></th>
 </tr>

 <% @cards.each do |card| %>
 <tr>
 	<th><%= card.original_text %></th>
 	<th><%= card.translated_text %></th>
 	<th><%= card.review_date %></th>
 	<th><%= link_to 'Edit', edit_card_path(card)%></th>
 	<th><%= link_to 'Delete', card_path(card), method: :delete, data: { confirm: "Are you sure?" } %></th>
 </tr>
 <% end %>

</table>

app/views/cards/new.html.erb
<%= simple_form_for @card do |f| %>
  <%= f.input :original_text %>
  <%= f.input :translated_text %>
  <%= f.button :submit %>
<% end %>

app/views/cards/show.html.erb
<h1><%= @card.original_text %></h1>

<div><%= @card.translated_text %></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Флэшкарточкер</title>
      <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
      <%= csrf_meta_tags %>
  </head>
  <body>
    
    <section id="container">
      <header class="clearfix">
        <h1>Флэшкарточкер</h1>
          <ul class="navigation-links">
            <li><%= link_to 'Все карточки', cards_path, class: 'btn btn-default' %></li>
            <li><%= link_to "Добавить карточку", new_card_path, class: 'btn btn-default' %></li>
          </ul>
      </header>
      <section>      
       <p style="font-size: 22px;" class="bg-success">Первый в мире удобный менеджер флеш-карточек. Именно так.</p>
        <%= yield %>
        
      </section>
   </section>
   
  </body>
</html>